### ISSUE TITLE
reset index of pd dataframe returned by thebeat.utils.get_ioi_df

### ISSUE THREAD

**Issue by Jellevanderwerff** [Jellevanderwerff/thebeat#58]
It seems the index is not reset after concatenating different dataframes

**Comment by YannickJadoul** [comment]
`ignore_index=True` (https://pandas.pydata.org/docs/reference/api/pandas.concat.html)

**Comment by Jellevanderwerff** [comment]
was no issue with the function but with the example, fixed in 841ca10
