### ISSUE TITLE
Few things wrong with the fft plots/values

### ISSUE THREAD

**Issue by Jellevanderwerff** [Jellevanderwerff/thebeat#89]
* The fft functions now return _amplitude_ rather than power (power = amplitude squared). Consider if we want to change the y axis label for the plotting functions, or rather actually return power.

* Relatedly, the returned values are now not mean-centred or detrended (so maximal power is at x=0). This is detrimental: the plot becomes unreadable, so likely one will set a value for x_min, though this is not the same as mean-centring or detrending, because the energy needed to recover from that peak at the beginning is very high. In other words, the shown plot becomes unintuitive/wrong when doing that. 

* We want to implement a default x_max that's srate / 2 (Nyquist).

* Lastly, the x_min and x_max parameters should be implemented in the fft functions, rather than only as the plotting limits.

**Comment by Jellevanderwerff** [comment]
In order:
* power is now returned (ff44117)
* dc offset removal has been added as an argument that defaults to False (offset not removed)
* Nyquist was already implemented of course
* There is no difference between the two options actually.

**Comment by YannickJadoul** [comment]
Link to #95

**Comment by Jellevanderwerff** [comment]
All fixed in #95
